server:
#  context-path: /hello
  port: 8082
webInfo:
  webName: 项目名字 Maven Demo
  structureWay: 构建方式 生产模式
spring:
  application: 
    name: Drs
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
    thymeleaf: 
      cache: false
      mode: LEGACYHTML5